name: Deploy Storefront

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps & build
        run: |
          cd apps/storefront
          npm ci
          npm run build

      - name: Build & push Docker (optional)
        uses: docker/build-push-action@v5
        with:
          context: ./apps/storefront
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/${{ github.repository }}-storefront:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker pull ${{ secrets.REGISTRY_HOST }}/${{ github.repository }}-storefront:latest
            docker stop storefront || true
            docker rm storefront || true
            docker run -d --restart unless-stopped --name storefront -p 3000:3000 ${{ secrets.REGISTRY_HOST }}/${{ github.repository }}-storefront:latest
