name: Deploy Payload CMS

on:
  push:
    paths:
      - 'cms/**'
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build Payload
        run: |
          cd cms
          npm ci
          npm run build

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./cms
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/${{ github.repository }}-payload:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker pull ${{ secrets.REGISTRY_HOST }}/${{ github.repository }}-payload:latest
            docker stop payload || true
            docker rm payload || true
            docker run -d --restart unless-stopped --name payload -p 4000:4000 \
            -e MONGO_URL="${{ secrets.MONGO_URL }}" \
            -e PAYLOAD_SECRET="${{ secrets.PAYLOAD_SECRET }}" \
            ${{ secrets.REGISTRY_HOST }}/${{ github.repository }}-payload:latest
