name: Deploy Worker

on:
  push:
    paths:
      - 'apps/worker/**'
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build & pack worker
        run: |
          cd apps/worker
          npm ci
          npm run build || echo "no build step"

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/worker
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/${{ github.repository }}-worker:latest

      - name: Deploy worker via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker pull ${{ secrets.REGISTRY_HOST }}/${{ github.repository }}-worker:latest
            docker stop worker || true
            docker rm worker || true
            docker run -d --restart unless-stopped --name worker \
            -e REDIS_URL="${{ secrets.REDIS_URL }}" \
            -e PAYLOAD_URL="${{ secrets.PAYLOAD_URL }}" \
            -e PAYLOAD_SECRET="${{ secrets.PAYLOAD_SECRET }}" \
            ${{ secrets.REGISTRY_HOST }}/${{ github.repository }}-worker:latest
